web/router.ex
defmodule BookSearch.Router do
  use BookSearch.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BookSearch do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/search", PageController, :show_search
    post "/search", PageController, :search

    resources "/posts", PostController, only: [:index]
    resources "/users", UserController, only: [:index]

    resources "/authors", AuthorController do
       resources "/books", BookController
    end
    resources "/categories", CategoryController
    resources "/books", BookController

  end

  # Other scopes may use custom stacks.
  # scope "/api", BookSearch do
  #   pipe_through :api
  # end
end

web/models/author.ex
defmodule BookSearch.Author do
  use BookSearch.Web, :model

  schema "authors" do
    field :name, :string
    field :email, :string
    has_many :books, BookSearch.Book

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :email])
    |> validate_required([:name])
    |> validate_length(:name, min: 2)
    |> validate_length(:name, max: 30)
    |> validate_length(:email, min: 5)
    |> validate_length(:email, max: 30)
    |> validate_format(:email, ~r/@/)
  end
end

web/controllers/author_controller.ex
defmodule BookSearch.AuthorController do
  use BookSearch.Web, :controller

  alias BookSearch.Author

  require Logger

  def index(conn, _params) do
    authors = Author |> Repo.all |> Repo.preload([:books])
    render(conn, "index.html", authors: authors)
  end

  def new(conn, _params) do
    changeset = Author.changeset(%Author{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"author" => author_params}) do
    changeset = Author.changeset(%Author{}, author_params)

    case Repo.insert(changeset) do
      {:ok, _author} ->
        conn
        |> put_flash(:info, "Author created successfully.")
        |> redirect(to: author_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    author = Repo.get!(Author, id) |> Repo.preload([:books])
    render(conn, "show.html", author: author)
  end

  def edit(conn, %{"id" => id}) do
    Logger.info "from_show #{conn.params["from_show"]}"
    author = Repo.get!(Author, id)
    changeset = Author.changeset(author)
    render(conn, "edit.html", author: author, changeset: changeset, from_show: conn.params["from_show"])
  end

  def update(conn, %{"id" => id, "author" => author_params}) do
    author = Repo.get!(Author, id)
    changeset = Author.changeset(author, author_params)

    case Repo.update(changeset) do
      {:ok, author} ->
        conn
        |> put_flash(:info, "Author updated successfully.")
        |> redirect(to: author_path(conn, :show, author))
      {:error, changeset} ->
        render(conn, "edit.html", author: author, changeset: changeset, from_show: conn.params["from_show"])
    end
  end

  def delete(conn, %{"id" => id}) do
    author = Repo.get!(Author, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(author)

    conn
    |> put_flash(:info, "Author deleted successfully.")
    |> redirect(to: author_path(conn, :index))
  end
end

web/views/author_view.ex
defmodule BookSearch.AuthorView do
  use BookSearch.Web, :view
end

web/templates/author/edit.html.eex
<h2>Edit author</h2>

<%= render "form.html", changeset: @changeset,
                        action: author_path(@conn, :update, @author) %>

<%= if @from_show do %>
<%= link " Back", to: author_path(@conn, :show, @author.id), class: "btn btn-default btn-xs fa fa-chevron-circle-left fa-2x" %>
<% else %>
<%= link " Back", to: author_path(@conn, :index), class: "btn btn-default btn-xs fa fa-chevron-circle-left fa-2x" %>
<% end %>

web/templates/author/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= submit " Submit", class: "btn btn-primary fa fa-2x fa-check-circle" %>
  </div>
<% end %>

web/templates/author/index.html.eex
<h2>Listing authors</h2>

<div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Books</th>

      <th class="three_button_width"></th>
    </tr>
  </thead>
  <tbody>
<%= for author <- @authors do %>
    <tr>
      <td><%= author.name %></td>
      <td><%= author.email %></td>
      <td><%= for book <- author.books do %>
          <%= book.title %>
          <br/>
      <% end %></td>

      <td class="text-right">
        <%= link "", to: author_path(@conn, :show, author), class: "btn btn-default btn-xs fa fa-eye fa-2x", title: "Show" %>
        <%= link "", to: author_path(@conn, :edit, author), class: "btn btn-default btn-xs  fa fa-edit fa-2x", title: "Edit" %>
        <%= link "", to: author_path(@conn, :delete, author), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs fa fa-trash fa-2x", title: "Delete" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
</div>
<%= link " New", to: author_path(@conn, :new), class: "btn btn-success btn-xs fa fa-plus-circle fa-2x" %>

web/templates/author/new.html.eex
<h2>New author</h2>

<%= render "form.html", changeset: @changeset,
                        action: author_path(@conn, :create) %>

<%= link " Back", to: author_path(@conn, :index), class: "btn btn-default btn-xs fa fa-chevron-circle-left fa-2x" %>

web/templates/author/show.html.eex
<h2>Show author</h2>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @author.name %>
  </li>

  <li>
    <strong>Email:</strong>
    <%= @author.email %>
  </li>

  <li>
    <strong>Books:</strong>
    <%= length(@author.books) %>
  </li>

  <%= for book <- @author.books do %>
      <a href="<%= book_path(@conn, :show, book.id) %>"><%= book.title %></a>
      <br/>
  <% end %>

  <br/>
  <%= link " Add book", to: author_book_path(@conn, :new, @author.id), class: "btn btn-success btn-xs fa fa-plus-circle fa-2x" %>
</ul>

<%= link " Back", to: author_path(@conn, :index), class: "btn btn-default btn-xs fa fa-chevron-circle-left fa-2x" %>
<%= link " Edit", to: author_path(@conn, :edit, @author, from_show: true), class: "btn btn-default btn-xs fa fa-edit fa-2x left-margin" %>