web/router.ex
defmodule BookSearch.Router do
  use BookSearch.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BookSearch do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/search", PageController, :show_search
    post "/search", PageController, :search

    resources "/posts", PostController, only: [:index]
    resources "/users", UserController, only: [:index]

    resources "/authors", AuthorController do
       resources "/books", BookController
    end
    resources "/categories", CategoryController
    resources "/books", BookController

  end

  # Other scopes may use custom stacks.
  # scope "/api", BookSearch do
  #   pipe_through :api
  # end
end

web/templates/page/index.html.eex
<div class="jumbotron index">
  <h2><%= gettext "Welcome to the book library" %></h2>
  <p class="lead">A library containing books and authors. Contains a search</p>
</div>
<div class="container">
<div class="row">
  <div class="col-sm-3">
    <a href="<%= page_path(@conn, :search) %>" class="index index_search">
      <span class="fa-stack fa-lg index_btn search_jumbo" aria-hidden="true" title="Search">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-search fa-stack-1x fa-inverse"></i>
        </span>
    </a>
  </div>
  <div class="col-sm-3">
    <a href="<%= book_path(@conn, :index) %>" class="index index_book">
      <span class="fa-stack fa-lg index_btn book_jumbo" aria-hidden="true" title="Books">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-book fa-stack-1x fa-inverse"></i>
        </span>
    </a>
  </div>
  <div class="col-sm-3">
    <a href="<%= author_path(@conn, :index) %>" class="index index_author">
      <span class="fa-stack fa-lg index_btn author_jumbo" aria-hidden="true" title="Authors">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-user fa-stack-1x fa-inverse"></i>
        </span>
    </a>
  </div>
  <div class="col-sm-3">
    <a href="<%= category_path(@conn, :index) %>" class="index index_category">
      <span class="fa-stack fa-lg index_btn category_jumbo" aria-hidden="true" title="Categories">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-tag fa-stack-1x fa-inverse"></i>
        </span>
    </a>
  </div>
</div>
</div>

web/templates/page/search.html.eex
<div class="jumbotron index">
  <h2><%= gettext "Search" %></h2>
  <p class="lead">Search books and authors</p>

  <%= form_for @conn, page_path(@conn, :search), [as: :search], fn f -> %>
    <%= text_input f, :search_term, class: "form-control", placeholder: "Search books and authors..." %>
    </br>
    <div class="form-group">
      <%= submit " Search", class: "btn btn-primary fa fa-2x fa-check-circle" %>
    </div>
  <% end %>
  <a href="#books">Jump to Books</a> |
  <a href="#authors"> Jump to Authors</a>
  </br>
</div>
  <a name="books"></a>
  <%= if length(@books) > 0 do %>
  <h2>Matching books</h2>
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th style="width:30%;">Title</th>
        <th>Isbn</th>
        <th>Year</th>
        <th>Author</th>
        <th>Categories</th>
        <th class="three_button_width"></th>
      </tr>
    </thead>
    <tbody>
  <%= for book <- @books do %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.isbn %></td>
        <td><%= book.year %></td>
        <td><%= book.author.name %></td>
        <td><%= for category <- book.categories do %>
            <%= category.name %>
            <br/>
        <% end %></td>
        <td class="text-right">
          <%= link "", to: book_path(@conn, :show, book), class: "btn btn-default btn-xs fa fa-eye fa-2x", title: "Show" %>
          <%= link "", to: book_path(@conn, :edit, book), class: "btn btn-default btn-xs  fa fa-edit fa-2x", title: "Edit" %>
          <%= link "", to: book_path(@conn, :delete, book), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs fa fa-trash fa-2x", title: "Delete" %>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>
</div>
  <% end %>

  </br>
  <a name="authors"></a>
  <%= if length(@authors) > 0 do %>
  <h2 name="authors">Matching authors</h2>
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Books</th>

        <th class="three_button_width"></th>
      </tr>
    </thead>
    <tbody>
  <%= for author <- @authors do %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.email %></td>
        <td><%= for book <- author.books do %>
            <%= book.title %>
            <br/>
        <% end %></td>

        <td class="text-right">
          <%= link "", to: author_path(@conn, :show, author), class: "btn btn-default btn-xs fa fa-eye fa-2x", title: "Show" %>
          <%= link "", to: author_path(@conn, :edit, author), class: "btn btn-default btn-xs  fa fa-edit fa-2x", title: "Edit" %>
          <%= link "", to: author_path(@conn, :delete, author), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs fa fa-trash fa-2x", title: "Delete" %>
        </td>
      </tr>
  <% end %>
    </tbody>
  </table>
</div>
  <% end %>